codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - develop
    - master

ignore:
  - "robustbench"
  - "setup.py"

coverage:
  status:
    project:
      default: false
    patch:
      default: false